export const pricingTiers = [
  {
    id: 'starter',
    name: 'Starter',
    price: '₹0.12',
    unit: '/msg',
    description: 'For businesses just starting with RCS',
    highlights: [
      'All 12 platform features',
      'Up to 3 agents',
      'Free Blue Tick verification',
      'Free onboarding on Jio & Vi',
      'Two-way communication',
      'Live delivery reports',
      'Campaign metrics (5-stage)',
    ],
    cta: 'Get started',
    ctaVariant: 'secondary',
    badge: null,
    popular: false,
  },
  {
    id: 'growth',
    name: 'Growth',
    price: '₹0.10',
    unit: '/msg',
    description: 'For teams scaling campaigns and automation',
    highlights: [
      'Everything in Starter',
      'AI Agent (intelligent replies)',
      'Drip campaigns & autoresponder',
      'Up to 10 agents',
      'No-code ChatBot builder',
      'API integration',
      'Advanced segmentation',
    ],
    cta: 'Start free trial',
    ctaVariant: 'primary',
    badge: 'Most popular',
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    unit: '',
    description: 'For high-volume senders and agencies',
    highlights: [
      'Everything in Growth',
      'Unlimited agents',
      'White-label dashboard',
      'Dedicated SLA',
      'Priority support',
      'Custom integrations',
      'Volume pricing',
    ],
    cta: 'Talk to sales',
    ctaVariant: 'secondary',
    badge: null,
    popular: false,
  },
];

export default pricingTiers;
